{
  "success": false,
  "run_id": 7,
  "eval": null,
  "duration_in_s": -1.0,
  "agent_answer": "Task failed due to [Errno Task timeout] 360.0 Traceback (most recent call last):\n  File \"/Users/apinto/dev/nottelabs/notte/src/notte_eval/run.py\", line 259, in compute_tasks\n    result = future.result()  # type: ignore\n             ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py\", line 456, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\nTimeoutError: [Errno Task timeout] 360.0\n",
  "task": {
    "question": "Find the paper 'GPT-4 Technical Report', when was v3 submitted?",
    "id": "webvoyager--ArXiv--17",
    "answer": "Mon, 27 Mar 2023 17:46:54 UTC",
    "url": "https://arxiv.org/",
    "website_name": "ArXiv"
  },
  "steps": [],
  "logs": {},
  "task_description": "Find the paper 'GPT-4 Technical Report', when was v3 submitted?",
  "task_id": "webvoyager--ArXiv--17",
  "task_website": "ArXiv",
  "reference_answer": "Mon, 27 Mar 2023 17:46:54 UTC",
  "total_input_tokens": 0,
  "total_output_tokens": 0,
  "last_message": ""
}